name: Java Maven Build & test
on:
  pull_request:
    branches: ['main']
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 24
      uses: actions/setup-java@v3
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: mvn clean package
      run: mvn clean package




